# Generated by Django 4.1.3 on 2022-11-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="discription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
